{{- if .Values.storage.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "media-engine.fullname" . }}-store
  labels:
    {{- include "media-engine.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
  {{- with .Values.storage.pvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
