apiVersion: v1
kind: Secret
metadata:
  name: {{ include "media-engine.fullname" . }}-db
  labels:
    {{- include "media-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.db.url | quote }}
